<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-CookingAPI-4e97f742-ffb2-4174-8f4b-a84fe1dda215</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.0.1" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" NoWarn="NU1605"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.12" NoWarn="NU1605"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12"/>
        <PackageReference Include="Microsoft.Identity.Web" Version="3.2.0"/>
        <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.2.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

     <ItemGroup>
        <ProjectReference Include="..\Cooking_Project\Cooking_Project.csproj" />
    </ItemGroup>

</Project>
